---
branches:
  only:
    - dev

sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker

before_install:
  - mkdir -p celesta-documentation/src/main/asciidoc/output
  - docker pull asciidoctor/docker-asciidoctor
  
install: true

script:
  - docker run -v $TRAVIS_BUILD_DIR/celesta-documentation/src/main/asciidoc/:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output 0000_Celesta.adoc
  - mvn -Dmaven.repo.remote=https://artifactory.corchestra.ru:443/artifactory/libs-release javadoc:javadoc

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_success:
  - cd celesta-documentation/src/main/asciidoc/output ; mv 0000_Celesta.html index.html ; cp -R ../images images
  - mv celesta-core/target/site/apidocs celesta-documentation/src/main/asciidoc/output/apidocs
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
