---
branches:
  only:
    - dev

sudo: required

language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - mvn --projects celesta-core javadoc:javadoc
  - mvn --projects celesta-documentation generate-resources

after_success:
  - mv celesta-core/target/site/apidocs celesta-documentation/target/generated-docs/apidocs
  - cd celesta-documentation/target/generated-docs
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
